name: Deploy to Preview Channel
on:
  pull_request:
    #branches:
    #  - 

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      #- name: Build Frontend - Bank App
      #  working-directory: ./frontend
      #  run: |
      #    npm ci
      #    npm start

      - name: Build Backend - Bank App
        working-directory: .
        run: |
          npm ci
          npm ci nodemon
          npm start

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          expires: 30d
          projectId: banking-app-61e33
          entryPoint: ./index.js
          firebaseToolsVersion: latest
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}